/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.search;

import com.biz.BillBiz;
import com.biz.BillBizImpl;
import com.biz.OrderBiz;
import com.biz.OrderBizImpl;
import com.po.Bill;
import com.po.Menu;
import com.po.Order;
import com.po.OrderDishes;
import com.util.StringUtil;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class SearchBillFrame extends javax.swing.JInternalFrame {

    OrderBiz obiz = new OrderBizImpl();
    BillBiz bbiz = new BillBizImpl();

    /**
     * Creates new form SearchBillFrame
     */
    public SearchBillFrame() {
        initComponents();
        initSearchMode();
    }

    private void initSearchMode() {
        //模拟从数据库中获取Title并填充到组合框
        String[] sex = {"顾客编号搜索", "服务员编号搜索"};
        for (String s : sex) {
            this.cobSelect.addItem(s);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        cobSelect = new javax.swing.JComboBox();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();

        setClosable(true);

        btnSearch.setText("搜索");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cobSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cobSelect.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(204, 153, 255)));
        cobSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cobSelectItemStateChanged(evt);
            }
        });

        txtSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(204, 153, 255)));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        tblOrder.setForeground(new java.awt.Color(51, 51, 51));
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "订单编号", "顾客编号", "顾客人数", "订单时间", "服务员编号", "餐桌编号", "房间编号", "实际金额", "结账时间"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrder);
        if (tblOrder.getColumnModel().getColumnCount() > 0) {
            tblOrder.getColumnModel().getColumn(0).setResizable(false);
            tblOrder.getColumnModel().getColumn(1).setResizable(false);
            tblOrder.getColumnModel().getColumn(2).setResizable(false);
            tblOrder.getColumnModel().getColumn(3).setResizable(false);
            tblOrder.getColumnModel().getColumn(4).setResizable(false);
            tblOrder.getColumnModel().getColumn(5).setResizable(false);
            tblOrder.getColumnModel().getColumn(6).setResizable(false);
            tblOrder.getColumnModel().getColumn(7).setResizable(false);
            tblOrder.getColumnModel().getColumn(8).setResizable(false);
        }

        btnClear.setText("清空");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cobSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnSearch))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(cobSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cobSelectItemStateChanged

    }//GEN-LAST:event_cobSelectItemStateChanged

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        this.getRootPane().setDefaultButton(btnSearch);
    }//GEN-LAST:event_txtSearchKeyPressed

    private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
//        this.txtActualPrice.setText("");
//        //鼠标选中某行，该行信息显示到输入面板
//        int row = this.tblOrder.getSelectedRow();
//        //        //根据row获取每列的值
//        this.txtOid.setText(this.tblOrder.getValueAt(row, 0) + "");
//        this.txtCid.setText(this.tblOrder.getValueAt(row, 1) + "");
//        this.txtCusNumber.setText(this.tblOrder.getValueAt(row, 2) + "");
//        this.txtOtime.setText(this.tblOrder.getValueAt(row, 3) + "");
//        this.txtTid.setText(this.tblOrder.getValueAt(row, 5) + "");
//        this.txtRid.setText(this.tblOrder.getValueAt(row, 6) + "");
//        this.txtTotalPrice.setText(this.tblOrder.getValueAt(row, 7) + "");

    }//GEN-LAST:event_tblOrderMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String content = this.cobSelect.getSelectedItem().toString().trim();
        if (StringUtil.checkLength(content) == false) {
            JOptionPane.showMessageDialog(this, "选项不能为空");
            return;
        }
        if (content.equals("顾客编号搜索")) {
            String cid = this.txtSearch.getText().trim();
            if (StringUtil.checkLength(cid) == false) {
                JOptionPane.showMessageDialog(this, "顾客编号不能为空");
                return;
            }
            int cid_int = Integer.parseInt(cid);
            List<Bill> blist = bbiz.findByCid(cid_int);
            showOnTable(blist);
            
        } else if (content.equals("服务员编号搜索")) {
            String eid = this.txtSearch.getText().trim();
            if (StringUtil.checkLength(eid) == false) {
                JOptionPane.showMessageDialog(this, "服务员编号不能为空");
                return;
            }    
            int eid_int = Integer.parseInt(eid);
            List<Bill> blist = bbiz.findByCid(eid_int);
            showOnTable(blist);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.tblOrder.getModel();
        //2.清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void showOnTable(List<Bill> blist) {
        //1.获取指定表格（tblOrder）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblOrder.getModel();
        //2.清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        //3.显示数据

        for (Bill b : blist) {
            Vector vt = new Vector();
            Order o = obiz.findFinishedByID(b.getBid());
            vt.add(o.getOid());
            vt.add(o.getCid());
            vt.add(o.getOpopulation());
            vt.add(o.getOtime());
            vt.add(o.getEid());
            vt.add(o.getTid());
            vt.add(o.getRid());
            vt.add(b.getBmoney());
            vt.add(b.getBtime());
            dtm.addRow(vt);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cobSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
