/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.order;
import com.biz.EmployeeBiz;
import com.biz.EmployeeBizImpl;
import com.biz.MenuBiz;
import com.biz.MenuBizImpl;
import com.biz.OrderBiz;
import com.biz.OrderBizImpl;
import com.biz.OrderDishesBiz;
import com.biz.OrderDishesBizImpl;
import com.biz.RoomBiz;
import com.biz.RoomBizImpl;
import com.biz.TableBiz;
import com.biz.TableBizImpl;
import com.po.Menu;
import com.po.Order;
import com.po.OrderDishes;
import com.po.Room;
import com.po.Table;
import com.util.StringUtil;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class OrderDishesByWaiterFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderDishesByWaiterFrame
     */
   OrderDishesBiz odbiz = new OrderDishesBizImpl();
     MenuBiz mbiz = new MenuBizImpl();
     OrderBiz obiz = new OrderBizImpl();
    public OrderDishesByWaiterFrame() {
        initComponents();
        this.btnShangcai.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDish = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnShangcai = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();

        setClosable(true);

        lblDish.setText("待上菜");

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "菜品名称", "菜品数量", "上菜桌号", "odid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        btnShangcai.setText("上菜");
        btnShangcai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShangcaiActionPerformed(evt);
            }
        });

        btnExit1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnExit1.setText("Exit");
        btnExit1.setToolTipText("关闭员工管理界面");
        btnExit1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(255, 51, 255), new java.awt.Color(204, 102, 255)));
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblDish)
                        .addGap(320, 320, 320)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnExit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnShangcai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDish)
                    .addComponent(btnSearch))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShangcai)
                .addGap(18, 18, 18)
                .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        List<OrderDishes> list = odbiz.findFinshed();
        showOnTable(list);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        int selectrow = this.tblMenu.getSelectedRow();
        this.btnShangcai.setEnabled(true);

    }//GEN-LAST:event_tblMenuMouseClicked

    private void btnShangcaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShangcaiActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        int selectrow = this.tblMenu.getSelectedRow();
        String mname = (String) this.tblMenu.getValueAt(selectrow, 0);
        Integer odcount = (Integer) this.tblMenu.getValueAt(selectrow, 1);
        Integer ntable = (Integer) this.tblMenu.getValueAt(selectrow, 2);
        Integer odid=(Integer)this.tblMenu.getValueAt(selectrow, 3);
        //Integer odid=(Integer)this.tblMenu.getValueAt(selectrow, 3);
        OrderDishes od=new OrderDishes(odid,null,null,odcount,null,4);
        boolean result=odbiz.Shangcai(od);
        if (result == true) {
            JOptionPane.showMessageDialog(this, "上菜成功");
            //刷新表格
            List<OrderDishes> list = odbiz.findFinshed();
            //显示list信息
            showOnTable(list);
        } else {
            JOptionPane.showMessageDialog(this, "上菜失败");
        }
    }//GEN-LAST:event_btnShangcaiActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
          int answer = JOptionPane.showConfirmDialog(this, "您确定要关闭吗？");
        if (answer == JOptionPane.YES_OPTION) {
            //界面恢复到最初状态
            clearInput();
            
            this.btnShangcai.setEnabled(false);
             
            //获取表格模型,清空表格信息
            DefaultTableModel dtm = (DefaultTableModel) this.tblMenu.getModel();
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            //关闭
            this.dispose();
        }
    }//GEN-LAST:event_btnExit1ActionPerformed
    private void showOnTable(List<OrderDishes> list) {
        //1.获取指定表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblMenu.getModel();
        //2.清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        //3.显示数据
        for(OrderDishes od : list){
            Vector vt=new Vector();
            Menu me= mbiz.findByMid(od.getMid());
            String name=me.getMname();
            vt.add(name);
            vt.add(od.getOdcount());
            Order o=obiz.findByID(od.getOid());
            Integer tid=o.getTid();
            vt.add(tid);
            vt.add(od.getOdid());
            dtm.addRow(vt);
        }   
    }
     private void clearInput() {
       
          tblMenu.clearSelection();
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShangcai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDish;
    private javax.swing.JTable tblMenu;
    // End of variables declaration//GEN-END:variables
}
