/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.order;

import com.biz.EmployeeBiz;
import com.biz.EmployeeBizImpl;
import com.biz.MenuBiz;
import com.biz.MenuBizImpl;
import com.biz.OrderBiz;
import com.biz.OrderBizImpl;
import com.biz.OrderDishesBiz;
import com.biz.OrderDishesBizImpl;
import com.biz.RoomBiz;
import com.biz.RoomBizImpl;
import com.biz.TableBiz;
import com.biz.TableBizImpl;
import com.biz.UserBiz;
import com.biz.UserBizImpl;
import com.po.Menu;
import com.po.Order;
import com.po.OrderDishes;
import com.po.Room;
import com.po.Table;
import com.po.User;
import com.util.StringUtil;
import com.view.MainFrame;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class OrderByWaiterFrame extends javax.swing.JInternalFrame {

    MenuBiz mbiz = new MenuBizImpl();
    OrderBiz obiz = new OrderBizImpl();
    TableBiz tbiz = new TableBizImpl();
    RoomBiz rbiz = new RoomBizImpl();
    OrderDishesBiz odbiz = new OrderDishesBizImpl();
    UserBiz ubiz = new UserBizImpl();
     public User userNew = null;//设置静态值对象，供界面传值用

    /**
     * Creates new form OrderByWaiter
     */
    public OrderByWaiterFrame() {
//        System.out.println("aaa");
        initComponents();
        initPurchaseTable();
        
    }
    
    public OrderByWaiterFrame(User user) {
//        System.out.println(user.getPermission());
        this.userNew = user;
        initComponents();
        initPurchaseTable();
        this.jScrollPane1.getViewport().setBackground(Color.WHITE);
        this.jScrollPane2.getViewport().setBackground(Color.WHITE);
        this.jScrollPane5.getViewport().setBackground(Color.WHITE);
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel1 = new com.view.HomePanel();
        lblMenu = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblMenu1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        lblCusNumber = new javax.swing.JLabel();
        txtCusNumber = new javax.swing.JTextField();
        lblTable = new javax.swing.JLabel();
        txtTable = new javax.swing.JTextField();
        lblRoom = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnCreateOrder = new javax.swing.JButton();
        lblMenu2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("顾客下单");

        lblMenu.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 51, 51));
        lblMenu.setText("菜单");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 255, 102));
        btnSearch.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblMenu1.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        lblMenu1.setForeground(new java.awt.Color(255, 51, 51));
        lblMenu1.setText("待下单");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "菜单编号", "菜品名称", "菜品类型", "菜品价格", "做菜时间"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMenu.getTableHeader().setReorderingAllowed(false);
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);
        if (tblMenu.getColumnModel().getColumnCount() > 0) {
            tblMenu.getColumnModel().getColumn(0).setResizable(false);
            tblMenu.getColumnModel().getColumn(1).setResizable(false);
            tblMenu.getColumnModel().getColumn(2).setResizable(false);
            tblMenu.getColumnModel().getColumn(3).setResizable(false);
            tblMenu.getColumnModel().getColumn(4).setResizable(false);
        }

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "菜单编号", "菜品名称", "菜品类型", "菜品价格", "做菜时间", "份数"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblOrder);
        if (tblOrder.getColumnModel().getColumnCount() > 0) {
            tblOrder.getColumnModel().getColumn(0).setResizable(false);
            tblOrder.getColumnModel().getColumn(1).setResizable(false);
            tblOrder.getColumnModel().getColumn(2).setResizable(false);
            tblOrder.getColumnModel().getColumn(3).setResizable(false);
            tblOrder.getColumnModel().getColumn(4).setResizable(false);
            tblOrder.getColumnModel().getColumn(5).setResizable(false);
        }

        btnDelete.setBackground(new java.awt.Color(255, 255, 102));
        btnDelete.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "桌子编号", "房间编号", "座位数"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTable.getTableHeader().setReorderingAllowed(false);
        tblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblTable);
        if (tblTable.getColumnModel().getColumnCount() > 0) {
            tblTable.getColumnModel().getColumn(0).setResizable(false);
            tblTable.getColumnModel().getColumn(1).setResizable(false);
            tblTable.getColumnModel().getColumn(2).setResizable(false);
        }

        lblCusNumber.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        lblCusNumber.setForeground(new java.awt.Color(255, 51, 51));
        lblCusNumber.setText("顾客人数");
        lblCusNumber.setToolTipText("员工姓名须由2-4个中文组成");

        txtCusNumber.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        txtCusNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(204, 153, 255)));
        txtCusNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCusNumberKeyPressed(evt);
            }
        });

        lblTable.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        lblTable.setForeground(new java.awt.Color(102, 102, 102));
        lblTable.setText("桌子编号");
        lblTable.setToolTipText("员工姓名须由2-4个中文组成");

        txtTable.setEditable(false);
        txtTable.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        txtTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(204, 153, 255)));
        txtTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTableKeyPressed(evt);
            }
        });

        lblRoom.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        lblRoom.setForeground(new java.awt.Color(102, 102, 102));
        lblRoom.setText("房间编号");
        lblRoom.setToolTipText("员工姓名须由2-4个中文组成");

        txtRoom.setEditable(false);
        txtRoom.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        txtRoom.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(204, 153, 255)));
        txtRoom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRoomKeyPressed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 102));
        btnUpdate.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        btnUpdate.setText("刷新");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCreateOrder.setBackground(new java.awt.Color(255, 255, 102));
        btnCreateOrder.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        btnCreateOrder.setText("生成订单");
        btnCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrderActionPerformed(evt);
            }
        });

        lblMenu2.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        lblMenu2.setForeground(new java.awt.Color(255, 51, 51));
        lblMenu2.setText("空闲桌子");

        javax.swing.GroupLayout homePanel1Layout = new javax.swing.GroupLayout(homePanel1);
        homePanel1.setLayout(homePanel1Layout);
        homePanel1Layout.setHorizontalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanel1Layout.createSequentialGroup()
                        .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(homePanel1Layout.createSequentialGroup()
                                .addComponent(lblMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(homePanel1Layout.createSequentialGroup()
                                .addComponent(lblMenu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, Short.MAX_VALUE))
                    .addGroup(homePanel1Layout.createSequentialGroup()
                        .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(homePanel1Layout.createSequentialGroup()
                                .addComponent(lblMenu2)
                                .addGap(175, 175, 175)
                                .addComponent(btnUpdate))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanel1Layout.createSequentialGroup()
                                .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(homePanel1Layout.createSequentialGroup()
                                        .addComponent(lblCusNumber)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCusNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(homePanel1Layout.createSequentialGroup()
                                        .addComponent(lblTable)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTable, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(homePanel1Layout.createSequentialGroup()
                                        .addComponent(lblRoom)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanel1Layout.createSequentialGroup()
                                .addComponent(btnCreateOrder)
                                .addGap(39, 39, 39))))))
        );
        homePanel1Layout.setVerticalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenu)
                    .addComponent(lblMenu1)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenu2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanel1Layout.createSequentialGroup()
                        .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCusNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCusNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoom))
                        .addGap(29, 29, 29)
                        .addComponent(btnCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        this.getRootPane().setDefaultButton(btnSearch);
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String condition = txtSearch.getText().trim();
        List<Menu> list = mbiz.findByCondition(condition);
        showOnTable(list);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        int selectrow = this.tblMenu.getSelectedRow();
        Integer mid = (Integer) this.tblMenu.getValueAt(selectrow, 0);
        String mname = (String) this.tblMenu.getValueAt(selectrow, 1);
        String mtype = (String) this.tblMenu.getValueAt(selectrow, 2);
        double mprice = (Double) this.tblMenu.getValueAt(selectrow, 3);
        Integer mcooktime = (Integer) this.tblMenu.getValueAt(selectrow, 4);
//        Integer mcount = (Integer) this.tblMenu.getValueAt(selectrow, 5);

        Vector vt = new Vector();
        vt.add(mid);
        vt.add(mname);
        vt.add(mtype);
        vt.add(mprice);
        vt.add(mcooktime);
//        vt.add(mcount);
        //添加到采购表格
        addOrderTable(vt);
    }//GEN-LAST:event_tblMenuMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = this.tblOrder.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "请输入要删除的记录！");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) this.tblOrder.getModel();
        dtm.removeRow(row);
        row = -1;
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        //获取信息
        DefaultTableModel dtm = (DefaultTableModel) this.tblOrder.getModel();
        //格式验证
        for (int row = 0; row < dtm.getRowCount(); row++) {
            if (this.tblOrder.getValueAt(row, 5) == null) {
                JOptionPane.showMessageDialog(this, "请选择份数！");
                return;
            }
            Menu m = mbiz.findByID(Integer.parseInt(this.tblOrder.getValueAt(row, 0).toString()));
            int mstorage = m.getMstorage();
            if (Integer.parseInt(this.tblOrder.getValueAt(row, 5).toString()) > mstorage) {
                JOptionPane.showMessageDialog(this, "份数超过了库存!");
                return;
            }
        }

        String cusNumber = this.txtCusNumber.getText().trim();
        if (StringUtil.checkLength(cusNumber) == false) {
            JOptionPane.showMessageDialog(this, "顾客人数不能为空");
            return;
        }
        if (StringUtil.checkDigit(cusNumber) == false) {
            JOptionPane.showMessageDialog(this, "顾客人数只能为数字");
            return;
        }
        if (StringUtil.checkLength(this.txtTable.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "餐桌编号不能为空");
            return;
        }
        if (StringUtil.checkLength(this.txtRoom.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "房间编号不能为空");
            return;
        }
        int tid = Integer.parseInt(this.txtTable.getText());
        int rid = Integer.parseInt(this.txtRoom.getText());
        int cusNumber_int = Integer.parseInt(cusNumber);

        Table t = tbiz.findByID(tid);
        Integer seat = t.getTseat();
        if (seat < cusNumber_int) {
            JOptionPane.showMessageDialog(this, "桌子无法容纳该人数");
            return;
        }
        //当前时间
        Date date = new Date();
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String time = format.format(date);

        Order o = new Order(null, cusNumber_int, time, userNew.getEid(), tid, rid);
        //生成订单，并获取订单对象
        boolean result_order = obiz.add(o);
        Order newOrder = obiz.findLastOne();

        //table类的修改
        t.setTcondition(0);
        boolean result_table = tbiz.update(t);

//        //Room类的修改。
//        int rrid = t.getRid();
//        Room room = rbiz.findByID(rrid);
//        int curcondition = room.getRcondition();
//        room.setRcondition(curcondition + 1);
//        boolean result_room = rbiz.update(room);

        for (int row = 0; row < dtm.getRowCount(); row++) {
            Integer oid = newOrder.getOid();
            Integer mid = (Integer) this.tblOrder.getValueAt(row, 0);
            Integer odcount = (Integer) this.tblOrder.getValueAt(row, 5);
            OrderDishes od = new OrderDishes(null, oid, mid, odcount, time, 1);
            odbiz.add(od);
            Menu m = mbiz.findByID(mid);
            mbiz.reduceMstorage(mid, odcount);
        }

        if (result_order == true) {
            JOptionPane.showMessageDialog(this, "创建订单成功");
        } else {
            JOptionPane.showMessageDialog(this, "创建订单失败");
        }
        clearUp();

    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void txtCusNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusNumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusNumberKeyPressed

    private void txtTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTableKeyPressed

    private void txtRoomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomKeyPressed

    private void tblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTableMouseClicked
        //鼠标选中某行，该行信息显示到输入面板
        int row = this.tblTable.getSelectedRow();
        //根据row获取每列的值
        this.txtTable.setText(this.tblTable.getValueAt(row, 0) + "");
        this.txtRoom.setText(this.tblTable.getValueAt(row, 1) + "");


    }//GEN-LAST:event_tblTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        List<Table> tlist = tbiz.findEmpty();
//        List<Room> rlist = rbiz.findByRcondition();
        showOnTable_tables(tlist);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void showOnTable(List<Menu> list) {
        //1.获取指定表格（tblMenu）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblMenu.getModel();
        //2.清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        //3.显示数据
        for (Menu m : list) {
            Vector vt = new Vector();
            vt.add(m.getMid());
            vt.add(m.getMname());
            vt.add(m.getMtype());
            vt.add(m.getMprice());
            vt.add(m.getMcooktime());
//            vt.add(m.getMcount());
            dtm.addRow(vt);
        }
    }

    //将tblMenu表中的选中信息添加到tblOrder表中
    private void addOrderTable(Vector vt) {
        boolean flag = false;
        DefaultTableModel dtm = (DefaultTableModel) this.tblOrder.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (vt.get(0) == tblOrder.getValueAt(i, 0)) {
                flag = true;
                break;
            }
        }
        if (flag == false) {
            dtm.addRow(vt);
        }
    }

    //将组合框添加到表中某列，并对组合框添加相应的items
    public void initPurchaseTable() {
        JComboBox cobsup = new JComboBox();
        List<Integer> numberlist = new ArrayList<Integer>();
        for (int i = 1; i < 6; i++) {
            numberlist.add(i);
        }

        for (Integer number : numberlist) {
            cobsup.addItem(number);
        }
        this.tblOrder.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(cobsup));

        //隐藏两列
        DefaultTableColumnModel dtm_order = (DefaultTableColumnModel) this.tblOrder.getColumnModel();
        dtm_order.getColumn(0).setMinWidth(0);
        dtm_order.getColumn(0).setMaxWidth(0);
        dtm_order.getColumn(3).setMinWidth(0);
        dtm_order.getColumn(3).setMaxWidth(0);
        dtm_order.getColumn(4).setMinWidth(0);
        dtm_order.getColumn(4).setMaxWidth(0);
        DefaultTableColumnModel dtm_menu = (DefaultTableColumnModel) this.tblMenu.getColumnModel();
        dtm_menu.getColumn(0).setMinWidth(0);
        dtm_menu.getColumn(0).setMaxWidth(0);

    }

    private void showOnTable_tables(List<Table> list) {
        //1.获取指定表格（tblMenu）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblTable.getModel();
        //2.清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        //3.显示数据
        for (Table t : list) {
            Vector vt = new Vector();
//            vt.add(m.getMid());
            vt.add(t.getTid());
            vt.add(t.getRid());
            vt.add(t.getTseat());
//            vt.add(m.getMcount());
            dtm.addRow(vt);
        }
    }

    private void clearUp() {
        this.txtCusNumber.setText("");
        this.txtTable.setText("");
        this.txtRoom.setText("");
        DefaultTableModel dtm_menu = (DefaultTableModel) this.tblMenu.getModel();
        DefaultTableModel dtm_order = (DefaultTableModel) this.tblOrder.getModel();
        DefaultTableModel dtm_table = (DefaultTableModel) this.tblTable.getModel();
        while (dtm_menu.getRowCount() > 0) {
            dtm_menu.removeRow(0);
        }
        while (dtm_order.getRowCount() > 0) {
            dtm_order.removeRow(0);
        }
        while (dtm_table.getRowCount() > 0) {
            dtm_table.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private com.view.HomePanel homePanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCusNumber;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblMenu2;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblTable;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtCusNumber;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTable;
    // End of variables declaration//GEN-END:variables
}
